name: PyPI Package
on:
  release:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generating distribution archives
      run: |
        python -m pip install --upgrade setuptools wheel
        python setup.py sdist bdist_wheel
    - name: Uploading the distribution archives
      run : |
        python -m pip install --upgrade twine
        python -m twine upload\
          -u ${{ secrets.TWINE_USERNAME }}\
          -p ${{ secrets.TWINE_PASSWORD }}\
          dist/*
